name: backend-prod-ci-cd
on:
  push:
    branches:
      - 'refactor/be/#242'
#    paths:
#     - 'backend/**'
jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      timestamp: ${{ steps.get-timestamp.outputs.timestamp }}
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: true
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: 도커 허브 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: 도커 이미지 태그에 쓰일 현재 timestamp 값 가져오기
        id: get-timestamp
        run: echo "timestamp=$(TZ='Asia/Seoul' date +%Y-%m-%d-%H-%M-%S)" >> $GITHUB_OUTPUT
      - name: 도커 이미지 빌드 & Push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/DockerFile-Prod
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dailry:prod_${{ steps.get-timestamp.outputs.timestamp }}

  deploy:
    needs: build
    runs-on: [ self-hosted, dailry-prod ]
    steps:
      - name: 배포 스크립트 실행
        run: |
          cd /home/ubuntu        #작업 디렉토리 변경. 변경하지 않으면 docker-compose 가 .env파일을 참조하지 않음.
          sudo /home/ubuntu/deploy.sh ${{ secrets.DOCKER_HUB_USERNAME }} ${{ needs.build.outputs.timestamp }}